### ISSUE TITLE
Option to compress datasets

### ISSUE THREAD

**Issue by jthorton** [openforcefield/qcsubmit#16]
__ISSUE__
While generating some test datasets such as the [informative set](https://github.com/openforcefield/qca-dataset-submission/pull/47) exporting the dataset can result in large json files. It might be nice to have an extra optional argument to allow compression of the files, this would also mean the reading of the files function should be adapted accordingly.

**Comment by jchodera** [comment]
I'm not sure this is the right question to be asking.  

What is the JSON used for? 

The [QCFractal API](http://docs.qcarchive.molssi.org/projects/QCFractal/en/stable/quickstart.html#Evaluating-a-Geometry-Optimization) accepts `dict` objects for specifying calculations to perform.

JSON is one way of serializing a `dict`, but (1) why are we serializing these instead of submitting them via the API, and (2) why did we reject other serialization schemes?

If we do need something "like JSON, but smaller", there are also other alternatives that are much more compact, like [BSON](http://bsonspec.org/), [MessagePack](https://msgpack.org/index.html), and [a bunch of others](https://www.lucidchart.com/techblog/2019/12/06/json-compression-alternative-binary-formats-and-compression-methods/), but I suspect this isn't actually what we want.

**Comment by jthorton** [comment]
Thanks for pointing to the alternatives.

1) This is to do with the submission process as the person that makes the dataset is not the same as the person that submits it so in the past datasets have been saved in this state before submitting. QCSubmit now also keeps a history of how the dataset was made in the JSON so its worth keeping around as it can tell us which molecules fail a certain step in the generation pipeline.

2) As QCSubmit is based on pydantic it comes free with the model but the others could easily be integrated as well, maybe similar to the toolkit we could have support for a few methods.

**Comment by jthorton** [comment]
This is now fixed as we now support multiple compression methods.
