### ISSUE TITLE
EnumerateStereoisomers adds same molecule twice if isomers are found and include_input=True

### ISSUE THREAD

**Issue by trevorgokey** [openforcefield/qcsubmit#38]
Using the EnumerateStereoisomers functionally allows the original molecule to be included:
```
        for molecule in molecules:
            try:
                isomers = molecule.enumerate_stereoisomers(
                    undefined_only=self.undefined_only,
                    max_isomers=self.max_isomers,
                    rationalise=self.rationalise,
                    toolkit_registry=toolkit,
                )
                if self.include_input:
                    result.add_molecule(molecule)

                for isomer in isomers:
                    result.add_molecule(isomer)
```
It appears that:
1. If no isomers are found and include_input=False, then no molecules are produced from this component. Does this mean there is no output from this component for downstream components? 
2. If a chiral center is found and isomers=2 and include_input=True, then 3 molecules are added. I am assuming the input here is identical to one of the stereoisomers.

**Comment by jthorton** [comment]
Yeah, this is a hard one, the way it is set up currently I was assuming the users first input was well defined and would want to enumerate all possible stereocenters and bonds but since the toolkit tries to remove the starting molecule from the return of the function the `include_input` accounts for this. See [here](https://github.com/openforcefield/openforcefield/blob/07ee344344c9f9364569b07e7dcfd157570a8fa9/openforcefield/utils/toolkits.py#L1007) for the toolkit implementation. If the users starting molecule has missing stereo then the toolkits behaviour is correct and we would not want to include the starting molecule. I think the best case here would be to remove the `include_input` flag and instead have a `defined_only` flag then we should check that all of the molecules have fully defined stereo before returning them. Until the toolkit has methods to detect problems with molecules we could do a simple molecule round trip and look out for undefined stereo errors raised by the toolkit?

**Comment by trevorgokey** [comment]
I agree that the `include_input` option can possibly be removed. I will play around with some of this; I think ultimately the goal of this component (for me, FWIW) is to generate a list of molecules if a SMILES string is ambiguous. 

The way I did this in my pipeline was to try to make an oFF molecule with `allow_undefined_stereo=False`, and if it failed, enumerate the stereoisomers outside of the toolkit in RDKit, then feed those SMILES into the oFF toolkit. It worked quite well.

**Comment by trevorgokey** [comment]
Thinking a few seconds longer, it should be possible to do something similar in the component using the toolkit wrappers.

**Comment by jthorton** [comment]
Yes I agree I think the component should run the enumeration and then return all fully defined molecules that pass an offmol round trip which may include the input Ill open a PR to reflect this.
