### ISSUE TITLE
Workflow Deduplication Errors.

### ISSUE THREAD

**Issue by jthorton** [openforcefield/qcsubmit#60]
After looking over an upcoming [qca submission](https://github.com/openforcefield/qca-dataset-submission/pull/162) that uses the tautomer and protomer enumeration workflow components we see that some molecules fail these stages. The molecules actually are enumerated by the toolkit correctly and the error happens in the deduplication stage in QCSubmit.

## Example 
The molecule `[H]c1c(c(nc(c1[H])C2=NN=N[N-]2)[H])[H]` 
![image](https://user-images.githubusercontent.com/30259414/99071936-fdf08b00-25aa-11eb-9622-56a286bd06fa.png)
failed the tautomer enumeration stage in the workflow but running this separately in the toolkit produces the following tautomers
![image](https://user-images.githubusercontent.com/30259414/99071898-e87b6100-25aa-11eb-98f1-5228ed5bfd9a.png)
with inchikey `ZKHJXYLAESJIEI-UHFFFAOYNA-N`
and 
![image](https://user-images.githubusercontent.com/30259414/99072043-2b3d3900-25ab-11eb-9905-5a0d4b623b61.png)
with inchikey `ZKHJXYLAESJIEI-UHFFFAOYNA-N`.

As the molecules are deduplicated during the workflow using the hydrogen specific inchkey this causes an error [here](https://github.com/openforcefield/qcsubmit/blob/5d1a3303ff2e5313b5b20ebc55333ec30d5e31b3/qcsubmit/datasets.py#L196) where make sure the molecules are fully isomorphic before collecting the conformers, this is the exception that then fails the molecule from the stage in the workflow. 

## Question
Is this actually a problem? I think both inchikey and QM would have the same point of view here that all 3 molecules are the same and I would expect the same results from a QM single point. They only difference might be if the toolkits generate different conformers for cases like this where optimization could result in different geometries but I don't think that would affect these simple molecules.  @trevorgokey @dotsdl would be good to get your thoughts on this one.

## Solution (if needed)
Originally I used the inchikey as this is toolkit independent but thinking about this more I think it would also be okay to use toolkit dependent canonical, isomeric, explicit hydrogen smiles to deduplicate the molecules as this process only happens when executing workflows, during this time the backend toolkit is consistent so the smiles comparison should be accurate as smiles generation is consistent.

**Comment by j-wags** [comment]
_based on discussion between @trevorgokey and I_

> Is this actually a problem? 

The only thing holding us back from saying "no" is knowing whether it's possible for two tautomers of a molecule to be not-readily-interconvertable. Put another way -- is there some arrangement of nuclei where there are two stable configurations of electrons possible? And are those two configurations of electrons ever stable on the millisecond-to-second timescale? @pavankum might know this, since it's probably a big assumption made in QC inputs.

If the answer the to above is "no" in all cases, then the above deduplication is DESIRED. 

If the answer to the above is "sometimes", then we need a more sophisticated solution, and in ambiguous cases, we should NOT deduplicate until we have better logic in place. Maybe InChI(Key) is this "sophisticated solution", but we should make sure, since we'll be stuck with this solution for a while. 

Until we can unambiguously say "no", then we should assume it's "sometimes", and our desired behavior should be to NOT deduplicate these.

**Recommendation**: So in this particular case, the desired behavior should be to produce three unique entries, each with a different CMILES, but which will almost certainly end up pointing to the same molecule in QCA (this is assuming the conformer generator produces the exact same conformer for each). 

In reality, all of these might really represent the "same" molecule in both MM and QM-land, but in our current infrastructure, different tools might consider these distinct, so if we only included one of these states when fitting a FF, then the FF might do a very poor job of parameterizing the other two.

**Comment by pavankum** [comment]
@j-wags sorry missed the notification among repo updates, electron transfer events occur at nano second level or below [1], there are some exceptions that occur in millisecond to microsecond range but never in millisecond-to-second timescale, so if that is the metric then this deduplication should not be a problem.

Regarding organic molecules of interest with intramolecular electron transfer: thiophene, imidazole, etc., pi-conjugated molecules are listed in ref 2 (again these events occur at picosecond to nanosecond level).

References:
[1] - https://pubs.acs.org/doi/10.1021/acs.chemrev.5b00298
[2] - https://dx.doi.org/10.1021/ct500527v

**Comment by j-wags** [comment]
> electron transfer events occur at nano second level or below [1], there are some exceptions that occur in millisecond to microsecond range but never in millisecond-to-second timescale, so if that is the metric then this deduplication should not be a problem

AWESOME! Thanks, @pavankum -- Absolutely perfect answer. 

**Recommendation:** Based on the info above, my new recommendation would be to deduplicate these (though having multiple entries that all point to the same molecule may actually be desired, and be more convenient for users). In the bigger picture, this indicates that InChI may be a better record of a molecule's graph than SMILES, and we may want to consider that in our infrastructure as we move forward.

**Comment by trevorgokey** [comment]
If the toolkit says there are tautomers, I am not sure if making QCSubmit opinionated is the right way to go. Could we possibly move this logic to the OFF tk? Would there be any downsides?

**Comment by pavankum** [comment]
@jthorton the issue with fragmented molecules from genentech set is similar to the one here, the molecules that give an error during de-duplication in `add_molecule()` function are
 `mol1 = Molecule.from_smiles('[H]c1c(c(c(c(c1[H])[H])[S+2](N([H])[H])([O-])[O-])[H])[H]')`
![image](https://user-images.githubusercontent.com/16142894/101390696-1422fb80-3878-11eb-8360-b1a755bf45dc.png)

and `mol2 = Molecule.from_smiles('[H]c1c(c(c(c(c1[H])[H])S(=O)(=O)N([H])[H])[H])[H]')`
![image](https://user-images.githubusercontent.com/16142894/101390747-2866f880-3878-11eb-9c81-dab964be08d9.png)

They both have the same inchi key `KHBQMWCZKVMBLN-IAUQMDSZNA-N` but are not isomorphic, and error out in the comparison [here](https://github.com/openforcefield/qcsubmit/blob/master/qcsubmit/datasets.py#L201)

**Comment by j-wags** [comment]
I think we should change this isomorphism check to have `formal_charge_matching=False, bond_order_matching=False, aromatic_matching=False`. This should be safe, since we _already know_ that the InChIs match, and so the possible isomorphism(s) should be valid.
